// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

// protoc --proto_path=$GOPATH/src --proto_path=.  --micro_out=. --go_out=.  rpc.proto
// 类似的包依赖一定要保证proto_path内至少有一个路径和源proto文件在一个目录

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AliceRequest struct {
	RevMsg               string   `protobuf:"bytes,1,opt,name=rev_msg,json=revMsg,proto3" json:"rev_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AliceRequest) Reset()         { *m = AliceRequest{} }
func (m *AliceRequest) String() string { return proto.CompactTextString(m) }
func (*AliceRequest) ProtoMessage()    {}
func (*AliceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *AliceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AliceRequest.Unmarshal(m, b)
}
func (m *AliceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AliceRequest.Marshal(b, m, deterministic)
}
func (m *AliceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AliceRequest.Merge(m, src)
}
func (m *AliceRequest) XXX_Size() int {
	return xxx_messageInfo_AliceRequest.Size(m)
}
func (m *AliceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AliceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AliceRequest proto.InternalMessageInfo

func (m *AliceRequest) GetRevMsg() string {
	if m != nil {
		return m.RevMsg
	}
	return ""
}

type AliceResponse struct {
	SendMsg              string   `protobuf:"bytes,1,opt,name=send_msg,json=sendMsg,proto3" json:"send_msg,omitempty"`
	RetCode              int32    `protobuf:"zigzag32,2,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AliceResponse) Reset()         { *m = AliceResponse{} }
func (m *AliceResponse) String() string { return proto.CompactTextString(m) }
func (*AliceResponse) ProtoMessage()    {}
func (*AliceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *AliceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AliceResponse.Unmarshal(m, b)
}
func (m *AliceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AliceResponse.Marshal(b, m, deterministic)
}
func (m *AliceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AliceResponse.Merge(m, src)
}
func (m *AliceResponse) XXX_Size() int {
	return xxx_messageInfo_AliceResponse.Size(m)
}
func (m *AliceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AliceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AliceResponse proto.InternalMessageInfo

func (m *AliceResponse) GetSendMsg() string {
	if m != nil {
		return m.SendMsg
	}
	return ""
}

func (m *AliceResponse) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

type BobRequest struct {
	RevMsg               string   `protobuf:"bytes,1,opt,name=rev_msg,json=revMsg,proto3" json:"rev_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BobRequest) Reset()         { *m = BobRequest{} }
func (m *BobRequest) String() string { return proto.CompactTextString(m) }
func (*BobRequest) ProtoMessage()    {}
func (*BobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *BobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BobRequest.Unmarshal(m, b)
}
func (m *BobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BobRequest.Marshal(b, m, deterministic)
}
func (m *BobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BobRequest.Merge(m, src)
}
func (m *BobRequest) XXX_Size() int {
	return xxx_messageInfo_BobRequest.Size(m)
}
func (m *BobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BobRequest proto.InternalMessageInfo

func (m *BobRequest) GetRevMsg() string {
	if m != nil {
		return m.RevMsg
	}
	return ""
}

type BobResponse struct {
	SendMsg              string   `protobuf:"bytes,1,opt,name=send_msg,json=sendMsg,proto3" json:"send_msg,omitempty"`
	RetCode              int32    `protobuf:"zigzag32,2,opt,name=ret_code,json=retCode,proto3" json:"ret_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BobResponse) Reset()         { *m = BobResponse{} }
func (m *BobResponse) String() string { return proto.CompactTextString(m) }
func (*BobResponse) ProtoMessage()    {}
func (*BobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *BobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BobResponse.Unmarshal(m, b)
}
func (m *BobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BobResponse.Marshal(b, m, deterministic)
}
func (m *BobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BobResponse.Merge(m, src)
}
func (m *BobResponse) XXX_Size() int {
	return xxx_messageInfo_BobResponse.Size(m)
}
func (m *BobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BobResponse proto.InternalMessageInfo

func (m *BobResponse) GetSendMsg() string {
	if m != nil {
		return m.SendMsg
	}
	return ""
}

func (m *BobResponse) GetRetCode() int32 {
	if m != nil {
		return m.RetCode
	}
	return 0
}

func init() {
	proto.RegisterType((*AliceRequest)(nil), "rpc.AliceRequest")
	proto.RegisterType((*AliceResponse)(nil), "rpc.AliceResponse")
	proto.RegisterType((*BobRequest)(nil), "rpc.BobRequest")
	proto.RegisterType((*BobResponse)(nil), "rpc.BobResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2a, 0x48, 0xd6,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e, 0x2a, 0x48, 0x56, 0x52, 0xe7, 0xe2, 0x71, 0xcc,
	0xc9, 0x4c, 0x4e, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe7, 0x62, 0x2f, 0x4a,
	0x2d, 0x8b, 0xcf, 0x2d, 0x4e, 0x97, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x2b, 0x4a, 0x2d,
	0xf3, 0x2d, 0x4e, 0x57, 0x72, 0xe5, 0xe2, 0x85, 0x2a, 0x2c, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15,
	0x92, 0xe4, 0xe2, 0x28, 0x4e, 0xcd, 0x4b, 0x41, 0x52, 0xca, 0x0e, 0xe2, 0xfb, 0x16, 0xa7, 0x83,
	0xa4, 0x8a, 0x52, 0x4b, 0xe2, 0x93, 0xf3, 0x53, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x04, 0x83,
	0xd8, 0x8b, 0x52, 0x4b, 0x9c, 0xf3, 0x53, 0x52, 0x95, 0x54, 0xb9, 0xb8, 0x9c, 0xf2, 0x93, 0x08,
	0xda, 0xe6, 0xcc, 0xc5, 0x0d, 0x56, 0x46, 0x89, 0x5d, 0x46, 0x16, 0x5c, 0xac, 0x60, 0x27, 0x0b,
	0xe9, 0x73, 0xb1, 0x04, 0x67, 0xe6, 0xa5, 0x0b, 0x09, 0xea, 0x81, 0x7c, 0x8f, 0xec, 0x5f, 0x29,
	0x21, 0x64, 0x21, 0x88, 0x6d, 0x4a, 0x0c, 0x46, 0xc6, 0x5c, 0xcc, 0x4e, 0xf9, 0x49, 0x42, 0x3a,
	0x5c, 0xac, 0x2e, 0x89, 0x79, 0xc9, 0xa9, 0x42, 0xfc, 0x60, 0x55, 0x08, 0x87, 0x4b, 0x09, 0x20,
	0x04, 0x60, 0x9a, 0x92, 0xd8, 0xc0, 0xc1, 0x6a, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xab, 0x18,
	0xe0, 0xb6, 0x63, 0x01, 0x00, 0x00,
}
